@startuml ヨットゲーム クラス図

class メインスクリーン {
    - メインスクリーン: Tk
    - 人数入力エントリ: CTk.Entry
    - ゲーム開始ボタン: CTk.Button

    + __init__()
    - start_game()
}

class ヨットゲーム {
    - ヨットゲーム: Tk
    - プレイヤー数: int
    - プレイヤー: list[Player]
    - ターン: int
    - ターン表示: CTk.Label
    - サイコロ: list[サイコロ]
    - サイコロ表示: CTk.Frame
    - サイコロボタン: CTk.Button
    - サイコロ回数: int
    - サイコロ回数表示: CTk.Label
    - サイコロリロールボタン: CTk.Button
    - プレイヤー表示: list
    - プレイヤー表示ラベル: list
    - プレイヤースコア設定ボタン: CTk.Button

    + __init__(プレイヤー数)
    - サイコロボタンクリック()
    - サイコロリロールボタンクリック()
    - プレイヤースコア設定ボタンクリック()
    - ターン表示更新()
    - サイコロ表示更新()
    - プレイヤー表示更新()
}

class プレイヤー {
    - プレイヤー名: str
    - スコア: int
    - スコア設定: int
    - スコア設定ボタン: CTk.Button

    + __init__(プレイヤー名)
    - スコア設定ボタンクリック()
}

class サイコロ {
    - サイコロ: Tk
    - サイコロ数: int
    - サイコロ値: list[int]
    - サイコロ表示: CTk.Label

    + __init__(サイコロ数)
    - サイコロ振る()
}

メインスクリーン --> ヨットゲーム: ゲーム開始
ヨットゲーム --> プレイヤー: 生成
ヨットゲーム --> サイコロ: 生成
ヨットゲーム --> ヨットゲーム: ターン進行

@enduml