@startuml シーケンス図
メインスクリーン --> ヨットゲーム: 生成・ゲーム開始

activate ヨットゲーム
ヨットゲーム --> サイコロフレーム: 生成
サイコロフレーム --> サイコロ: 生成
サイコロ --> サイコロボタン: 生成
サイコロフレーム --> サイコロ振り直しボタン: 生成

ヨットゲーム --> プレイヤースコアフレーム: 生成
プレイヤースコアフレーム --> プレイヤースコア: 生成
プレイヤースコアフレーム --> プレイヤースコア表示ラベル: 生成
プレイヤースコアフレーム --> プレイヤースコア設定ボタン: 生成

ヨットゲーム --> サイコロフレーム: 表示
ヨットゲーム --> プレイヤースコアフレーム: 表示

' (ターン処理) ここから 12回繰り返す
loop 12回
    ヨットゲーム --> サイコロフレーム: サイコロを振る
    deactivate ヨットゲーム

    サイコロボタン --> サイコロ: 押された
    サイコロ --> サイコロ: 振り直し対象の切り替え
    サイコロ振り直しボタン --> ヨットゲーム: 押された
    activate ヨットゲーム
    ヨットゲーム --> サイコロ: サイコロを振り直す
    サイコロ --> ヨットゲーム: サイコロの目を取得
    deactivate ヨットゲーム

    プレイヤースコア設定ボタン --> ヨットゲーム: 押された
    activate ヨットゲーム
    ヨットゲーム --> プレイヤースコア: スコアを設定
    プレイヤースコア --> プレイヤースコア表示ラベル: スコアを表示
    ヨットゲーム --> ヨットゲーム: ターンを進める
end
@enduml